"""
GrantStar — Curated Grant Database
A comprehensive database of real grants relevant to African applicants.
Each grant includes eligibility, funding range, sectors, deadlines, and difficulty ratings.
"""

GRANTS = [
    # ─── GLOBAL GRANTS ───────────────────────────────────────────────────
    {
        "id": "tef_2026",
        "name": "Tony Elumelu Foundation Entrepreneurship Programme",
        "funder": "Tony Elumelu Foundation",
        "type": "Grant + Mentorship",
        "amount_usd": {"min": 5000, "max": 5000},
        "currency": "USD",
        "deadline": "2026-03-31",
        "sectors": ["Agri", "Tech", "Health", "Education", "Manufacturing", "Creative", "Energy"],
        "eligible_countries": ["ALL_AFRICA"],
        "excluded_countries": [],
        "org_types": ["Startup"],
        "stages": ["Idea", "Early"],
        "url": "https://www.tonyelumelufoundation.org/programme",
        "description": "Seed capital, mentorship, and business training for African entrepreneurs. "
                       "One of the most accessible programmes for early-stage African founders.",
        "required_docs": {
            "ALL": ["Business Plan", "Government-Issued ID", "Passport Photo"],
            "Nigeria": ["CAC Certificate", "TIN"],
            "Kenya": ["KRA PIN Certificate", "Business Registration Certificate"],
            "South Africa": ["CIPC Registration", "SARS Tax Clearance"],
            "Ghana": ["RGD Certificate", "TIN"],
        },
        "difficulty": 2,
        "tags": ["africa-only", "seed-funding", "mentorship"],
    },
    {
        "id": "google_org_ai",
        "name": "Google.org AI for Social Good",
        "funder": "Google.org",
        "type": "Grant",
        "amount_usd": {"min": 50000, "max": 2000000},
        "currency": "USD",
        "deadline": "2026-06-30",
        "sectors": ["Tech", "Health", "Education", "Environment"],
        "eligible_countries": ["ALL_GLOBAL"],
        "excluded_countries": ["Iran", "North Korea", "Syria", "Cuba"],
        "org_types": ["NGO", "Research", "Startup"],
        "stages": ["Early", "Growth"],
        "url": "https://www.google.org/",
        "description": "Funding for organizations using AI to address social challenges. "
                       "Strong preference for projects with measurable impact in underserved communities.",
        "required_docs": {
            "ALL": ["Organization Registration", "Tax Exemption Certificate", "Project Proposal",
                    "Financial Statements (2 years)", "Team CVs"],
            "Nigeria": ["CAC Certificate", "TIN", "SCUML Certificate"],
            "Kenya": ["NGO Coordination Board Certificate", "KRA PIN"],
            "South Africa": ["NPO Certificate", "BBBEE Certificate", "SARS Tax Clearance"],
        },
        "difficulty": 7,
        "tags": ["ai", "technology", "global", "competitive"],
    },
    {
        "id": "gates_gchallenges",
        "name": "Bill & Melinda Gates Foundation — Grand Challenges",
        "funder": "Bill & Melinda Gates Foundation",
        "type": "Grant",
        "amount_usd": {"min": 100000, "max": 1000000},
        "currency": "USD",
        "deadline": "2026-05-15",
        "sectors": ["Health", "Agri", "Education"],
        "eligible_countries": ["ALL_GLOBAL"],
        "excluded_countries": [],
        "org_types": ["NGO", "Research", "Startup"],
        "stages": ["Early", "Growth"],
        "url": "https://gcgh.grandchallenges.org/",
        "description": "Supports bold ideas to solve global health and development challenges. "
                       "Special interest in Sub-Saharan Africa and South Asia.",
        "required_docs": {
            "ALL": ["Detailed Research Proposal", "Institutional Letter of Support",
                    "Lead PI CV", "Budget Justification", "Ethics Approval (if applicable)"],
            "Nigeria": ["CAC Certificate", "TIN", "SCUML Certificate"],
            "Kenya": ["KRA PIN", "CR12"],
            "South Africa": ["CIPC Registration", "BBBEE Certificate"],
        },
        "difficulty": 8,
        "tags": ["health", "research", "high-impact", "global"],
    },
    {
        "id": "usaid_dca",
        "name": "USAID Development Innovation Ventures (DIV)",
        "funder": "USAID",
        "type": "Grant",
        "amount_usd": {"min": 25000, "max": 15000000},
        "currency": "USD",
        "deadline": "2026-07-01",
        "sectors": ["Agri", "Health", "Education", "Tech", "Energy", "Finance"],
        "eligible_countries": ["ALL_GLOBAL"],
        "excluded_countries": [],
        "org_types": ["NGO", "Research", "Startup"],
        "stages": ["Idea", "Early", "Growth"],
        "url": "https://www.usaid.gov/div",
        "description": "Tiered funding (Stage 1: $25K-$200K, Stage 2: $200K-$1.5M, Stage 3: up to $15M). "
                       "Rigorous evidence-based approach. Strong track record with African organizations.",
        "required_docs": {
            "ALL": ["SAM.gov Registration", "DUNS Number", "Project Proposal",
                    "Monitoring & Evaluation Plan", "Budget Narrative"],
            "Nigeria": ["CAC Certificate", "TIN", "SCUML Certificate", "Audited Financial Statements"],
            "Kenya": ["KRA PIN", "CR12", "NGO Board Certificate"],
            "South Africa": ["CIPC Registration", "BBBEE Certificate", "SARS Tax Clearance"],
        },
        "difficulty": 9,
        "tags": ["evidence-based", "tiered", "us-government", "scalable"],
    },
    {
        "id": "eu_horizon_africa",
        "name": "EU Horizon Europe — Africa Initiative",
        "funder": "European Commission",
        "type": "Grant",
        "amount_usd": {"min": 100000, "max": 3000000},
        "currency": "EUR",
        "deadline": "2026-09-15",
        "sectors": ["Tech", "Health", "Environment", "Energy", "Agri"],
        "eligible_countries": ["ALL_GLOBAL"],
        "excluded_countries": [],
        "org_types": ["Research", "NGO", "Startup"],
        "stages": ["Early", "Growth"],
        "url": "https://ec.europa.eu/info/horizon-europe",
        "description": "Europe's flagship R&I programme. African organizations can participate "
                       "as partners in consortia. Requires a European lead partner.",
        "required_docs": {
            "ALL": ["EU PIC Number Registration", "Partnership Agreement",
                    "Research Proposal (Part A & B)", "Consortium Description"],
            "Nigeria": ["CAC Certificate", "TIN"],
            "Kenya": ["KRA PIN", "CR12"],
            "South Africa": ["CIPC Registration", "BBBEE Certificate", "NRF Endorsement"],
        },
        "difficulty": 9,
        "tags": ["european-union", "research", "consortium", "partnership-required"],
    },
    {
        "id": "mastercard_scholars",
        "name": "Mastercard Foundation Scholars Program",
        "funder": "Mastercard Foundation",
        "type": "Scholarship + Grant",
        "amount_usd": {"min": 10000, "max": 50000},
        "currency": "USD",
        "deadline": "2026-04-30",
        "sectors": ["Education", "Tech", "Agri", "Health"],
        "eligible_countries": ["ALL_AFRICA"],
        "excluded_countries": [],
        "org_types": ["Individual", "Research"],
        "stages": ["Idea", "Early"],
        "url": "https://mastercardfdn.org/all/scholars/",
        "description": "Comprehensive scholarship for young Africans with academic talent "
                       "and a commitment to giving back. Covers tuition, living expenses, and mentorship.",
        "required_docs": {
            "ALL": ["Academic Transcripts", "Personal Statement", "Recommendation Letters (2)",
                    "Proof of Financial Need", "Community Engagement Evidence"],
            "Nigeria": ["WAEC/NECO Results", "JAMB Score", "LGA Indigene Letter"],
            "Kenya": ["KCSE Results", "Helb Statement"],
            "South Africa": ["Matric Certificate", "NSFAS Application"],
        },
        "difficulty": 5,
        "tags": ["scholarship", "youth", "africa-only", "education"],
    },
    {
        "id": "afdb_boost_africa",
        "name": "AfDB Boost Africa — Innovation Fund",
        "funder": "African Development Bank (AfDB)",
        "type": "Equity + Grant",
        "amount_usd": {"min": 50000, "max": 500000},
        "currency": "USD",
        "deadline": "2026-08-31",
        "sectors": ["Tech", "Agri", "Finance", "Energy"],
        "eligible_countries": ["ALL_AFRICA"],
        "excluded_countries": [],
        "org_types": ["Startup"],
        "stages": ["Early", "Growth"],
        "url": "https://www.afdb.org/en/topics-and-sectors/initiatives-partnerships/boost-africa",
        "description": "Supports innovative African enterprises through a combination of equity "
                       "investment and grant funding. Focuses on job creation and economic transformation.",
        "required_docs": {
            "ALL": ["Business Registration", "Pitch Deck", "Financial Projections (3 years)",
                    "Cap Table", "Founder ID"],
            "Nigeria": ["CAC Certificate", "TIN", "SCUML Certificate"],
            "Kenya": ["KRA PIN", "CR12", "Business Registration"],
            "South Africa": ["CIPC Registration", "BBBEE Certificate"],
            "Ghana": ["RGD Certificate", "TIN"],
        },
        "difficulty": 6,
        "tags": ["africa-only", "equity", "innovation", "job-creation"],
    },
    {
        "id": "kofi_annan_ict",
        "name": "Kofi Annan Award for Innovation in Africa",
        "funder": "Kofi Annan Foundation",
        "type": "Award + Grant",
        "amount_usd": {"min": 25000, "max": 100000},
        "currency": "USD",
        "deadline": "2026-05-31",
        "sectors": ["Tech", "Health", "Education", "Agri"],
        "eligible_countries": ["ALL_AFRICA"],
        "excluded_countries": [],
        "org_types": ["Startup", "Individual"],
        "stages": ["Idea", "Early", "Growth"],
        "url": "https://www.kofiannanfoundation.org/",
        "description": "Recognizes and supports African innovators using technology to solve "
                       "pressing challenges on the continent. Strong media exposure for winners.",
        "required_docs": {
            "ALL": ["Innovation Description", "Impact Report", "Founder CV", "Demo/Prototype Link"],
            "Nigeria": ["CAC Certificate (if registered)"],
            "Kenya": ["Business Registration (if registered)"],
            "South Africa": ["CIPC Registration (if registered)"],
        },
        "difficulty": 4,
        "tags": ["innovation", "award", "africa-only", "media-exposure"],
    },
    # ─── LOCAL / REGIONAL GRANTS ─────────────────────────────────────────
    {
        "id": "ng_youwin",
        "name": "YouWiN! Connect Nigeria",
        "funder": "Federal Government of Nigeria",
        "type": "Grant",
        "amount_usd": {"min": 1500, "max": 25000},
        "currency": "NGN",
        "deadline": "2026-06-30",
        "sectors": ["Agri", "Tech", "Manufacturing", "Creative", "Health"],
        "eligible_countries": ["Nigeria"],
        "excluded_countries": [],
        "org_types": ["Startup", "Individual"],
        "stages": ["Idea", "Early"],
        "url": "https://youwin.ng/",
        "description": "Federal Government enterprise support programme. "
                       "Competitive but highly accessible for Nigerian entrepreneurs under 40.",
        "required_docs": {
            "ALL": ["Business Plan", "Government-Issued ID"],
            "Nigeria": ["CAC Certificate", "TIN", "BVN", "Passport Photo",
                        "Birth Certificate or Age Declaration"],
        },
        "difficulty": 3,
        "tags": ["nigeria-only", "youth", "government", "accessible"],
    },
    {
        "id": "ng_nitda",
        "name": "NITDA Technology Innovation & Entrepreneurship Support",
        "funder": "NITDA (Nigeria)",
        "type": "Grant + Incubation",
        "amount_usd": {"min": 5000, "max": 50000},
        "currency": "NGN",
        "deadline": "2026-08-15",
        "sectors": ["Tech"],
        "eligible_countries": ["Nigeria"],
        "excluded_countries": [],
        "org_types": ["Startup"],
        "stages": ["Idea", "Early"],
        "url": "https://nitda.gov.ng/",
        "description": "NITDA supports Nigerian tech startups with grants, incubation space, "
                       "and access to markets. Focus on locally-relevant technology solutions.",
        "required_docs": {
            "ALL": ["Pitch Deck", "Product Demo/MVP"],
            "Nigeria": ["CAC Certificate", "TIN", "NITDA IT Registration"],
        },
        "difficulty": 3,
        "tags": ["nigeria-only", "tech", "government", "incubation"],
    },
    {
        "id": "ke_ajira",
        "name": "Ajira Digital Programme — Kenya",
        "funder": "Government of Kenya / World Bank",
        "type": "Grant + Training",
        "amount_usd": {"min": 2000, "max": 10000},
        "currency": "KES",
        "deadline": "2026-12-31",
        "sectors": ["Tech", "Creative"],
        "eligible_countries": ["Kenya"],
        "excluded_countries": [],
        "org_types": ["Individual", "Startup"],
        "stages": ["Idea", "Early"],
        "url": "https://ajiradigital.go.ke/",
        "description": "Government programme supporting Kenyan youth in digital economy. "
                       "Provides training, workspace, and seed funding for digital businesses.",
        "required_docs": {
            "ALL": ["National ID", "Business Proposal"],
            "Kenya": ["KRA PIN", "Business Registration (optional for individuals)"],
        },
        "difficulty": 2,
        "tags": ["kenya-only", "digital", "youth", "government"],
    },
    {
        "id": "za_seda",
        "name": "SEDA Technology Programme — South Africa",
        "funder": "Small Enterprise Development Agency (SEDA)",
        "type": "Grant + Incubation",
        "amount_usd": {"min": 5000, "max": 30000},
        "currency": "ZAR",
        "deadline": "2026-10-31",
        "sectors": ["Tech", "Manufacturing", "Agri", "Creative"],
        "eligible_countries": ["South Africa"],
        "excluded_countries": [],
        "org_types": ["Startup"],
        "stages": ["Idea", "Early"],
        "url": "https://www.seda.org.za/",
        "description": "SEDA provides business development support to South African SMMEs "
                       "including incubation, mentorship, and technology transfer.",
        "required_docs": {
            "ALL": ["Business Plan", "Director ID"],
            "South Africa": ["CIPC Registration", "BBBEE Certificate", "SARS Tax Clearance",
                             "Municipal Account"],
        },
        "difficulty": 4,
        "tags": ["south-africa-only", "incubation", "government", "smme"],
    },
    {
        "id": "gh_neip",
        "name": "National Entrepreneurship & Innovation Plan (NEIP) — Ghana",
        "funder": "Government of Ghana",
        "type": "Grant + Training",
        "amount_usd": {"min": 2000, "max": 15000},
        "currency": "GHS",
        "deadline": "2026-09-30",
        "sectors": ["Agri", "Tech", "Manufacturing", "Creative"],
        "eligible_countries": ["Ghana"],
        "excluded_countries": [],
        "org_types": ["Startup", "Individual"],
        "stages": ["Idea", "Early"],
        "url": "https://neip.gov.gh/",
        "description": "Ghana's flagship entrepreneurship support programme. Provides seed capital, "
                       "business development services, and access to markets.",
        "required_docs": {
            "ALL": ["Business Plan", "Ghana Card"],
            "Ghana": ["RGD Certificate", "TIN", "SSNIT Registration"],
        },
        "difficulty": 3,
        "tags": ["ghana-only", "government", "youth", "accessible"],
    },
    {
        "id": "vc4a_launch",
        "name": "VC4A Launch Africa Programme",
        "funder": "VC4A (Venture Capital for Africa)",
        "type": "Grant + Mentorship",
        "amount_usd": {"min": 10000, "max": 50000},
        "currency": "USD",
        "deadline": "2026-07-31",
        "sectors": ["Tech", "Finance", "Health", "Agri", "Energy"],
        "eligible_countries": ["ALL_AFRICA"],
        "excluded_countries": [],
        "org_types": ["Startup"],
        "stages": ["Early", "Growth"],
        "url": "https://vc4a.com/",
        "description": "Pan-African venture support platform connecting startups with funding, "
                       "mentorship, and investor networks. Strong emphasis on scalable business models.",
        "required_docs": {
            "ALL": ["Pitch Deck", "Financial Model", "Traction Metrics", "Team Bios"],
            "Nigeria": ["CAC Certificate"],
            "Kenya": ["Business Registration", "CR12"],
            "South Africa": ["CIPC Registration"],
            "Ghana": ["RGD Certificate"],
        },
        "difficulty": 5,
        "tags": ["africa-only", "venture", "mentorship", "scalable"],
    },
]


# ─── COUNTRY-SPECIFIC DOCUMENT KNOWLEDGE BASE ────────────────────────────────

COUNTRY_DOCS = {
    "Nigeria": {
        "tax_id": "Tax Identification Number (TIN) — obtainable from FIRS",
        "registration": "Certificate of Incorporation — from Corporate Affairs Commission (CAC)",
        "compliance": "SCUML Certificate — Special Control Unit against Money Laundering",
        "financial": "Audited Financial Statements — from a registered Chartered Accountant",
        "id": "National ID (NIN), International Passport, or Voter's Card",
        "bank": "Bank Verification Number (BVN)",
        "extras": [
            "Memorandum & Articles of Association (MEMART)",
            "CAC Status Report (Form CAC 1.1)",
            "Board Resolution (for grants > $50K)"
        ],
    },
    "Kenya": {
        "tax_id": "KRA PIN Certificate — from Kenya Revenue Authority",
        "registration": "Certificate of Registration — from Business Registration Service (BRS)",
        "compliance": "CR12 — Company Registry extract showing directors & shareholders",
        "financial": "Audited Accounts — from a CPA Kenya member",
        "id": "National ID Card or Passport",
        "bank": "Bank Statement (6 months)",
        "extras": [
            "NGO Coordination Board Certificate (for NGOs)",
            "KRA Tax Compliance Certificate",
            "County Business Permit"
        ],
    },
    "South Africa": {
        "tax_id": "SARS Tax Clearance Certificate — from South African Revenue Service",
        "registration": "CIPC Registration Certificate — Companies and Intellectual Property Commission",
        "compliance": "BBBEE Certificate — Broad-Based Black Economic Empowerment verification",
        "financial": "Annual Financial Statements — IFRS compliant",
        "id": "South African ID or Passport",
        "bank": "Bank Confirmation Letter",
        "extras": [
            "NPO Certificate (for non-profits)",
            "PBO Approval (for tax-exempt status)",
            "Municipal Account (proof of address)"
        ],
    },
    "Ghana": {
        "tax_id": "TIN — from Ghana Revenue Authority (GRA)",
        "registration": "RGD Certificate — from Registrar General's Department",
        "compliance": "Social Security (SSNIT) Registration",
        "financial": "Audited Financial Statements — from ICAG member",
        "id": "Ghana Card (National ID)",
        "bank": "Bank Statement (6 months)",
        "extras": [
            "EPA Environmental Permit (if applicable)",
            "FDA Registration (for health/food sectors)",
            "Business Operating Permit"
        ],
    },
    "Rwanda": {
        "tax_id": "TIN — from Rwanda Revenue Authority (RRA)",
        "registration": "RDB Certificate — Rwanda Development Board",
        "compliance": "RDB Compliance Certificate",
        "financial": "Audited Financial Statements",
        "id": "National ID",
        "bank": "Bank Statement (6 months)",
        "extras": [
            "Investment Certificate (for foreign-funded projects)",
            "Environmental Impact Assessment (if applicable)"
        ],
    },
    "Tanzania": {
        "tax_id": "TIN — from Tanzania Revenue Authority (TRA)",
        "registration": "BRELA Certificate — Business Registrations and Licensing Agency",
        "compliance": "TRA Tax Clearance",
        "financial": "Audited Accounts — from NBAA registered auditor",
        "id": "National ID (NIDA) or Passport",
        "bank": "Bank Statement (6 months)",
        "extras": [
            "NGO Registration Certificate (for NGOs)",
            "Local Government Permit"
        ],
    },
}


# ─── SDG TRANSLATION MAP ─────────────────────────────────────────────────────

IMPACT_TRANSLATIONS = {
    "market women": {
        "sdgs": ["SDG 5: Gender Equality", "SDG 8: Decent Work & Economic Growth"],
        "global_terms": ["Women's Economic Empowerment", "Financial Inclusion",
                         "Gender-Responsive Enterprise Development"],
    },
    "smallholder farmers": {
        "sdgs": ["SDG 2: Zero Hunger", "SDG 1: No Poverty"],
        "global_terms": ["Climate-Smart Agriculture", "Smallholder Value Chain Integration",
                         "Food Systems Transformation"],
    },
    "youth empowerment": {
        "sdgs": ["SDG 4: Quality Education", "SDG 8: Decent Work & Economic Growth"],
        "global_terms": ["Youth Workforce Development", "Skills-Based Employment Pathways",
                         "Digital Literacy & Inclusion"],
    },
    "health": {
        "sdgs": ["SDG 3: Good Health & Well-Being"],
        "global_terms": ["Primary Healthcare Strengthening", "Health Systems Resilience",
                         "Universal Health Coverage"],
    },
    "clean energy": {
        "sdgs": ["SDG 7: Affordable & Clean Energy", "SDG 13: Climate Action"],
        "global_terms": ["Distributed Renewable Energy", "Energy Access & Transition",
                         "Off-Grid Solar Solutions"],
    },
    "education": {
        "sdgs": ["SDG 4: Quality Education"],
        "global_terms": ["Inclusive & Equitable Education", "EdTech for Last-Mile Learners",
                         "21st Century Skills Development"],
    },
    "fintech": {
        "sdgs": ["SDG 1: No Poverty", "SDG 10: Reduced Inequalities"],
        "global_terms": ["Financial Inclusion", "Digital Financial Services",
                         "Mobile Money & Payment Infrastructure"],
    },
    "water": {
        "sdgs": ["SDG 6: Clean Water & Sanitation"],
        "global_terms": ["WASH (Water, Sanitation & Hygiene)", "Water Resource Management",
                         "Community-Led Total Sanitation"],
    },
    "environment": {
        "sdgs": ["SDG 13: Climate Action", "SDG 15: Life on Land"],
        "global_terms": ["Climate Resilience", "Ecosystem Restoration",
                         "Nature-Based Solutions"],
    },
    "manufacturing": {
        "sdgs": ["SDG 9: Industry, Innovation & Infrastructure"],
        "global_terms": ["Inclusive Industrialization", "Local Value Addition",
                         "Sustainable Manufacturing"],
    },
}
